In [25]:
x = [20, 40, 60, 80]
y = [20, 40, 60, 80]
print(x == y, x is y)

True False


In [2]:
stop = 7
result = 0
for n in range(10):
    result += n+2
    if result > stop:
        break
    print(n)
print(result)

0
1
9


In [3]:
result = 0
for n in range(7):
    result = n-4
    if (result % 2) != 0:
        print('-', end=' ')
        continue
    print(result, end=' ')
print('done')

-4 - -2 - 0 - 2 done


In [4]:
a = 2
b=24
c=22
result = 0
while a<b:
    result = a*2
    print(result)
    if result > c:
        break
    a+=4

4
12
20
28


In [6]:
stop = 11
result = 0
for a in range(5):
    for b in range(4):
        result += a+b
    print(result)
    if result > stop:
        break

6
16


In [8]:
stop = 8
result = 0
for a in range(4):
    print(a, end=': ')
    for b in range(2):
        result += a + b
        if result > stop:
            print('-', end=" ")
            continue
        print(result, end=" ")
    print()

0: 0 1 
1: 2 4 
2: 6 - 
3: - - 


In [11]:
result = 0
n = 2
while n < 5:
    print(n, end=' ')
    result += 4
    n += 1
else:
    print('/ {}'.format(result))
print("done")

2 3 4 / 12
done


In [13]:
result = 0
n = 1
while n < 8:
    print(n, end=" ")
    result -= 3
    if result < -8:
        
        print('*')
        break
    n += 1
else:
    print('/ {}'.format(result))
print('done')

1 2 3 *
done


In [15]:
result = 0
for n in range(3):
    print(n, end=' ')
    result -= 2
else:
    print('\ {}'.format(result))
print('done')

0 1 2 \ -6
done


In [16]:
stop = 7
total = 0
for number in [2,5,6,3,7,5]:
    print(number, end=' ')
    total += number
    if total > stop:
        print('!')
        break
else:
    print('/ {}'.format(total))
print('done')

2 5 6 !
done


In [19]:
colors = ['red', 'black', 'green', 'yellow']
for (position, color) in enumerate(colors):
    print(position, color)

0 red
1 black
2 green
3 yellow


In [5]:
def f(a,b=4):    
    r = a + b    
    print(r) 

f(3)

7


In [14]:
x = 100
def f():    
    x = x + 10 

f()
print(x)

UnboundLocalError: local variable 'x' referenced before assignment

In [11]:
def f(a, b=5, c=10):
   return a + b + c

In [12]:
f(1,2)

13

In [20]:
for num in range(-2,-5,-1):
    print(num, end=", ")

-2, -3, -4, 

In [21]:
#This is a comment

In [32]:
def f(*num):
    print('works')

In [34]:
x = "700"
print(x.isdigit())

True


In [4]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)
print(a)
print()
print(b)

[[0. 0.]
 [0. 0.]]

[[1. 0.]
 [0. 1.]]


In [5]:
b = np.mat([[5, 6], [7, 8]])
np.dtype(b)

TypeError: data type not understood

In [6]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]
print(b)

[1, 3, 2, 4]


In [7]:
a = np.matrix([[1, 0], [2, -1]])
r = a * a
print(r)

[[1 0]
 [0 1]]


In [11]:
a = np.ones(2)
b = np.ones((1,2))
print(a)
print()
print(b)

[1. 1.]

[[1. 1.]]


In [12]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [14]:
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)
print(b)

[1 2 3 4 5 6]


In [15]:
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1, 0]
a[0,0]= a[0,2] + a[2,0]
print(a)

[[10  2  3]
 [ 4 10  6]
 [ 7  8  0]]


In [19]:
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I
print(x)
print()
print(y)

[[1. 0.]
 [0. 0.]]

[[1. 1.]
 [2. 0.]]


In [20]:
a = np.zeros((2,2))

b = np.eye(2)

print(a)
print()
print(b)

[[0. 0.]
 [0. 0.]]

[[1. 0.]
 [0. 1.]]


In [21]:
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [22]:
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [23]:
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I
print(x)
print()
print(y)

[[1. 0.]
 [0. 0.]]

[[1. 1.]
 [2. 0.]]


In [24]:
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
print(b)

[[ 7  8]
 [11 12]]


In [25]:
a = np.array([[1, 0], [2, -1]])
r = a * a
print(r)

[[1 0]
 [4 1]]


In [26]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]
print(a)

[[ 5  7  3  2  1]
 [ 6  4  8  9 10]]


In [27]:
a = np. array([ [1, 2], [3, 4] ]) 
print(np.mean(a, axis=None)== np.mean(a))

True


In [28]:
np.random.random((2,2))

array([[0.01539178, 0.46050832],
       [0.69587259, 0.06478986]])

In [29]:
a = np.array([[1,2,3], [4,5,6]])
b = a.T
print(b)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [32]:
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
b

array([[ 7,  8],
       [11, 12]])