# Nicholas Early
## week 10
### Python numpy intro

In [1]:
import numpy as np

In [2]:
np.version

<module 'numpy.version' from 'c:\\Miniconda\\envs\\py37_default\\lib\\site-packages\\numpy\\version.py'>

In [3]:
np.__version__

'1.18.5'

In [4]:
arr = np.array([1,2,3,4,5,6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr1 = np.array([1,2,3,4,5,6])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
#0-D arrays
arr2 = np.array(50)

In [12]:
arr2

array(50)

In [14]:
print(arr2)

50


In [15]:
#1-D Arrays

In [16]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
# 2-D Array - Matrix
arr4 = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [21]:
#3-D Array
arr5 = np.array([[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]]])
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [22]:
print(arr2.ndim)

0


In [23]:
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)

1
2
3


In [24]:
# array indexing
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
print(arr3[1])

2


In [26]:
print(arr3[-1])

10


In [27]:
print(arr[0] + arr[3])

5


In [28]:
# 2-D indexing
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [29]:
print(arr4[0,1])

2


In [30]:
print(arr4 [-1,-1])

66


In [31]:
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [32]:
print(arr5[0,1,1])

5


In [33]:
print(arr5[1,0,-1])

33


In [34]:
marr = np.array([1,2,3,4,5], ndmin=5)

In [36]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [37]:
#slicing np arrays
#[start:end] step is assumed 1
#[start:end:step]
#[:end] start is 0, step is 1
#[start:] end is the length of the array

In [38]:
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
print(arr3[1:4])

[2 3 4]


In [40]:
print(arr3[3:])

[ 4  5  6  7  8  9 10]


In [41]:
print(arr[:3])

[1 2 3]


In [43]:
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [47]:
print(arr3[-3:-1])

[8 9]


In [48]:
print(arr3[1:5:2])

[2 4]


In [49]:
print(arr3[::2])

[1 3 5 7 9]


In [50]:
#slicing 2-D arrays
print(arr4.ndim)

2


In [51]:
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [52]:
print(arr4[1,1:3])

[22 33]


In [53]:
print(arr4[:,1:3])

[[ 2  3]
 [22 33]]
