# Nicholas Early
## week 10
### python numpy array processing

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]
print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
my_arr = np.array(my_list)

In [4]:
print(my_arr.dtype)

int32


In [5]:
fruits = ['Orange','Apple','Cherry','Grape']
my_strArr = np.array(fruits)

In [6]:
print(my_strArr.dtype)

<U6


In [7]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [8]:
print(my_arr2.dtype)

|S2


In [9]:
my_arr3 = np.array([5,6,7,8,9], dtype='i4')

In [10]:
print(my_arr3.dtype)

int32


In [11]:
scores = [78.5,88.9,90.3,89.9]
my_arr = np.array(scores)
print(my_arr)

[78.5 88.9 90.3 89.9]


In [12]:
arr = my_arr.astype('i')
print(arr)

[78 88 90 89]


In [13]:
arr = np.array([1,0,0,3,4,5,6,7,0])


In [14]:
print(arr.dtype)

int32


In [15]:
bool_arr = arr.astype(bool)
print(bool_arr)

[ True False False  True  True  True  True  True False]


In [16]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]
my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)


[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [18]:
#numpy built-in functions to generate arrays from existing arrays
#copy and view instead fo using =
mylst = [1,2,3,4,5,6]
arr = np.array(mylst)
c_arr = arr.copy()

print(arr)
print(c_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [20]:
arr[3] = 10
print(arr)
print(c_arr)

[ 1  2  3 10  5  6]
[1 2 3 4 5 6]


In [21]:
arr = np.array(mylst)
v_arr = arr.view()

print(arr)
print(v_arr)

arr[4] = 10

print(arr)
print(v_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[ 1  2  3  4 10  6]
[ 1  2  3  4 10  6]


In [22]:
v_arr[3] = 20

print(arr)
print(v_arr)

[ 1  2  3 20 10  6]
[ 1  2  3 20 10  6]


In [23]:
print(c_arr.base)
print(v_arr.base)

None
[ 1  2  3 20 10  6]


In [24]:
#shape gives number of elements in each dimension

In [25]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]
my_arr = np.array(my_list)

my_arr.shape

(2, 5)