# Nicholas Early
## Week 11
### Python NumPy Universal Functions

In [3]:
import numpy as np

In [6]:
arr1 = [1,2,3,4,5,6,7,8,9]
arr2 = [11,12,13,14,15,16,17,18,19]
z=[]
for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [7]:
#zip

fname = ('Alice', 'Bob', 'Christy')
lname = ('Charlie', 'Clark', 'Robert')

In [8]:
flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [9]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [2]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
arr1 = np.random.randn(10)
arr1

array([ 0.90923992,  0.13483401,  0.14064274, -0.03367538, -0.02556526,
        1.48301814,  0.65177413, -0.50254694, -0.65106115, -0.81211999])

In [6]:
arr2 = np.random.randn(10)
arr2

array([-1.46288864, -0.81431035, -0.08024453,  0.26638323, -1.20546518,
       -0.38345622, -1.23501747, -1.59526817,  0.57857212,  0.41769202])

In [7]:
np.add(arr1,arr2)

array([-0.55364872, -0.67947634,  0.06039821,  0.23270785, -1.23103043,
        1.09956192, -0.58324333, -2.09781511, -0.07248903, -0.39442797])

In [8]:
np.maximum(arr1,arr2)

array([ 0.90923992,  0.13483401,  0.14064274,  0.26638323, -0.02556526,
        1.48301814,  0.65177413, -0.50254694,  0.57857212,  0.41769202])

In [9]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [11]:
print(np.where(arr<4, -1, 10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [12]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [14]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [15]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20,  3,  4, 50])

In [16]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [17]:
np.where([[True,False],[True,True]],[[5,6],[7,8]],[[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [19]:
from numpy.random import randn
arr = randn(5,5)
arr 

array([[-0.62604883, -0.65372832,  0.06942968,  0.52913   , -1.70854145],
       [ 0.07290779, -0.04195278, -1.36306921,  0.34824973,  0.25058053],
       [-0.47829049, -0.97114223,  1.09741538,  1.83395038,  1.25922848],
       [-0.49084122,  0.51311494,  0.08360978, -0.94830494,  0.92676559],
       [ 0.04624279,  0.06720626, -0.29598564, -0.24955266,  0.00285767]])

In [20]:
np.where(arr<0,arr,0)

array([[-0.62604883, -0.65372832,  0.        ,  0.        , -1.70854145],
       [ 0.        , -0.04195278, -1.36306921,  0.        ,  0.        ],
       [-0.47829049, -0.97114223,  0.        ,  0.        ,  0.        ],
       [-0.49084122,  0.        ,  0.        , -0.94830494,  0.        ],
       [ 0.        ,  0.        , -0.29598564, -0.24955266,  0.        ]])

In [22]:
arr_b = np.array([True,False,True,False,False])

arr_b.any()

True

In [23]:
arr_b.all()

False

In [24]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [26]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
arr.sum()

45

In [29]:
arr.sum(0)

array([12, 15, 18])

In [30]:
arr.sum(1)

array([ 6, 15, 24])

In [31]:
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [32]:
arr.mean()

5.0

In [33]:
arr.mean(1)

array([2., 5., 8.])

In [34]:
arr.var()

6.666666666666667

In [35]:
arr.std()

2.581988897471611

In [36]:
arr.sort()

In [38]:
i = np.eye(5,5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
m = np.mat([[1,2],[3,4]])
np.dtype(m)

TypeError: data type not understood

In [43]:
#Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)
print('-----------------------')
t = arr.T
t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
-----------------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [46]:
arr_3d = np.arange(20).reshape((2,5,2))
print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [48]:
np.random.random((4,4))

array([[0.02264209, 0.33772487, 0.29373585, 0.5543489 ],
       [0.61235783, 0.51179863, 0.15086166, 0.77734332],
       [0.57284411, 0.41953669, 0.54523531, 0.18886193],
       [0.61188101, 0.59017484, 0.05298729, 0.77296556]])

In [50]:
from numpy.random import random
random((4,4))

array([[0.82784123, 0.73323293, 0.22909717, 0.8530159 ],
       [0.49651371, 0.18546749, 0.26495979, 0.31599326],
       [0.17621124, 0.48371481, 0.04871229, 0.48552654],
       [0.80876095, 0.27371047, 0.74142512, 0.04555478]])

In [51]:
from numpy.random import randn
randn(5,5)

array([[-1.43055241,  0.27892659,  0.23618395, -0.73748588, -0.67116309],
       [ 0.95274498,  0.38681404,  2.07354305, -1.47355135, -0.73248554],
       [-0.86038289,  1.76762134,  0.77765259,  1.40315563, -0.01905136],
       [ 0.65824136, -0.24965559,  0.49889407, -0.62632468,  0.11489167],
       [ 0.86098962,  0.60701596, -0.70586141, -1.23904369, -0.46601201]])

In [52]:
randn(5)

array([-0.41504606, -1.03267141, -1.22051142,  0.1110989 , -0.71582456])

In [53]:
np.random.randint(10,50)

49

In [54]:
import pandas as pd