# Nicholas Early
## Week 11
### Python NumPy Universal Functions

In [1]:
import numpy as np

In [6]:
arr1 = [1,2,3,4,5,6,7,8,9]
arr2 = [11,12,13,14,15,16,17,18,19]
z=[]
for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [7]:
#zip

fname = ('Alice', 'Bob', 'Christy')
lname = ('Charlie', 'Clark', 'Robert')

In [8]:
flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [9]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [10]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
arr1 = np.random.randn(10)
arr1

array([-0.80080183, -0.05667715, -2.2875489 ,  0.55729332,  1.31626207,
       -0.83971678, -1.18101033,  0.34451556,  0.74729679, -2.00588812])

In [15]:
arr2 = np.random.randn(10)
arr2

array([-2.58825905, -0.07704392, -1.4119156 ,  0.28953835,  0.37057958,
       -0.61942909, -1.31826223, -0.72905343, -0.356562  , -0.53365987])

In [16]:
np.add(arr1,arr2)

array([-3.38906088, -0.13372108, -3.69946451,  0.84683167,  1.68684165,
       -1.45914587, -2.49927256, -0.38453787,  0.39073478, -2.53954799])

In [17]:
np.maximum(arr1,arr2)

array([-0.80080183, -0.05667715, -1.4119156 ,  0.55729332,  1.31626207,
       -0.61942909, -1.18101033,  0.34451556,  0.74729679, -0.53365987])

In [18]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [21]:
print(np.where(arr<4, -1, 10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [22]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [23]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [25]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [27]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20,  3,  4, 50])